(()=>{
const extra=document.createElement('style');extra.textContent=`
.mealTabs{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.mealTab{border:1px solid var(--line);background:#fff;border-radius:14px;padding:11px 4px 9px;font-size:13px;font-weight:900;color:#5f5147;min-height:58px;touch-action:manipulation}.mealTab.active{border:2px solid var(--orange);background:#fff5eb;color:#a94c0a}.mealTabStatus{display:flex;justify-content:center;gap:3px;margin-top:6px}.mealTabDot{width:14px;height:14px;border-radius:50%;font-size:8px;display:grid;place-items:center;font-weight:900;color:#8b8076;background:#f1ece7}.mealTabDot.on.g1{background:var(--g1);color:#333}.mealTabDot.on.g2{background:var(--g2);color:#333}.mealTabDot.on.g3{background:var(--g3);color:#333}.mealTabDot.on.g4{background:var(--g4);color:#333}
.mealWorkspace{padding:14px;margin-top:10px}.mealWorkspace h2{margin:0 0 10px;font-size:18px}.groupSummary{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:12px}.groupCard{border:1px solid var(--line);border-radius:14px;padding:10px 4px;text-align:center;min-width:0}.groupCard strong{display:block;font-size:18px}.groupCard small{display:block;font-size:9px;line-height:1.3;margin-top:3px}.groupCard b{display:block;font-size:21px;margin-top:7px}.groupCard.g1{background:var(--g1)}.groupCard.g2{background:var(--g2)}.groupCard.g3{background:var(--g3)}.groupCard.g4{background:var(--g4)}
.breakdownTitle{font-size:14px;font-weight:900;margin:16px 2px 8px}.breakGroup{border:1px solid var(--line);border-left:5px solid #aaa;border-radius:14px;background:#fff;margin-top:8px;overflow:hidden}.breakGroup.g1{border-left-color:#66a9ee}.breakGroup.g2{border-left-color:#ef7e93}.breakGroup.g3{border-left-color:#75b965}.breakGroup.g4{border-left-color:#efa53b}.breakHead{display:flex;justify-content:space-between;align-items:center;padding:10px 12px;font-weight:900}.breakHead span{font-size:11px;color:#777;font-weight:700}.subGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:0 10px 10px}.subItem{position:relative;border:1px solid #e7ded6;border-radius:12px;background:#fffaf7;padding:11px 8px;text-align:center;min-height:76px;touch-action:manipulation}.subItem .name{font-size:12px;font-weight:800;line-height:1.35}.subItem .num{font-size:21px;font-weight:900;margin-top:5px}.subItem .unit{font-size:10px;color:#777}.subItem .minus{position:absolute;right:5px;bottom:5px;border:0;border-radius:999px;width:28px;height:28px;background:#f3eee9;color:#6b5544;font-size:18px;font-weight:900}.subItem:active{transform:scale(.985)}.subHint{font-size:10px;color:#777;padding:0 12px 10px}.photoRow{margin-top:10px}.footnav>div{grid-template-columns:repeat(5,1fr)!important}.footnav button{font-size:10px!important;padding-left:1px!important;padding-right:1px!important}.healthHero{padding:16px;margin-bottom:12px;background:linear-gradient(135deg,#fff5e9,#fff);border:1px solid var(--line);border-radius:18px}.healthHero h2{font-size:19px;margin:0 0 7px}.healthHero p{font-size:13px;line-height:1.7;margin:0;color:#65574c}
.guideWheelWrap{padding:14px}.guideWheel{position:relative;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;width:min(330px,90vw);aspect-ratio:1;margin:6px auto 14px;border-radius:50%;overflow:hidden;border:6px solid #fff;box-shadow:0 4px 18px rgba(70,45,20,.10)}.guideQuad{border:0;font-weight:900;font-size:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px}.guideQuad small{font-size:11px}.guideQuad.g1{background:var(--g1)}.guideQuad.g2{background:var(--g2)}.guideQuad.g3{background:var(--g3)}.guideQuad.g4{background:var(--g4)}.guideWheelCenter{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:112px;height:112px;border-radius:50%;background:#fff;display:flex;align-items:center;justify-content:center;text-align:center;font-weight:900;box-shadow:0 3px 12px rgba(70,45,20,.10)}
`;document.head.appendChild(extra);

window.__activeMealId='breakfast';
const defs={
  1:[['milk','牛乳・乳製品'],['egg','卵']],
  2:[['fish','魚介類'],['meat','肉'],['beans','豆・豆製品']],
  3:[['veg','野菜'],['mush','きのこ・海藻'],['potato','いも'],['fruit','果物']],
  4:[['staple','米・パン・めん'],['seasoning','砂糖・調味料'],['fat','油脂類'],['other','酒・その他']]
};
function ensureSub(m){
  if(!m.subCounts)m.subCounts={1:{},2:{},3:{},4:{}};
  [1,2,3,4].forEach(g=>{if(!m.subCounts[g])m.subCounts[g]={};defs[g].forEach(([k])=>{if(!Number.isFinite(Number(m.subCounts[g][k])))m.subCounts[g][k]=0})});
}
function syncTotals(m){
  ensureSub(m);
  m.groupCounts=m.groupCounts||{1:0,2:0,3:0};
  [1,2,3].forEach(g=>m.groupCounts[g]=defs[g].reduce((s,[k])=>s+(Number(m.subCounts[g][k])||0),0));
  m.p4=Math.round(defs[4].reduce((s,[k])=>s+(Number(m.subCounts[4][k])||0),0)*2)/2;
  const has=[1,2,3].filter(g=>m.groupCounts[g]>0);if(m.p4>0)has.push(4);m.groups=has;
}
function totalFor(m,g){ensureSub(m);return defs[g].reduce((s,[k])=>s+(Number(m.subCounts[g][k])||0),0)}
function cardLabel(g){return g===1?'乳・卵':g===2?'魚・肉・豆':g===3?'野菜など':'主食・油など'}

render=function(){
  document.getElementById('dateLabel').textContent=fmt(current);const d=dayData();const wrap=document.getElementById('meals');
  const tabs=`<div class="mealTabs">${mealDefs.map(([id,label])=>{const m=d[id];ensureSub(m);syncTotals(m);return `<button type="button" class="mealTab ${window.__activeMealId===id?'active':''}" data-mealtab="${id}">${label}<span class="mealTabStatus">${[1,2,3,4].map(g=>`<i class="mealTabDot g${g} ${totalFor(m,g)>0?'on':''}">${g}</i>`).join('')}</span></button>`}).join('')}</div>`;
  const found=mealDefs.find(x=>x[0]===window.__activeMealId)||mealDefs[0],id=found[0],label=found[1],m=d[id];ensureSub(m);syncTotals(m);
  const summary=`<div class="groupSummary">${[1,2,3,4].map(g=>`<div class="groupCard g${g}"><strong>${g}群</strong><small>${cardLabel(g)}</small><b>${totalFor(m,g)}${g===4?'点':''}</b></div>`).join('')}</div>`;
  const breaks=[1,2,3,4].map(g=>`<div class="breakGroup g${g}"><div class="breakHead">${g}群 <span>${cardLabel(g)}・タップで追加</span></div><div class="subGrid">${defs[g].map(([k,n])=>{const v=Number(m.subCounts[g][k])||0;return `<button type="button" class="subItem" data-subadd="${g}:${k}"><div class="name">${n}</div><div class="num">${v}<span class="unit">${g===4?'点':'回'}</span></div><span class="minus" data-subminus="${g}:${k}">−</span></button>`}).join('')}</div>${g===4?'<div class="subHint">4群は1回のタップで0.5点加算します。</div>':''}</div>`).join('');
  wrap.innerHTML=tabs+`<div class="card mealWorkspace"><h2>${label}</h2><div class="photoRow"><img class="preview" ${m.img?`src="${m.img}" style="display:block"`:''}><label class="photo">📷 ${m.img?'写真を変更':'写真を追加'}<input type="file" accept="image/*" capture="environment" hidden></label></div>${summary}<div class="breakdownTitle">内訳を記録</div>${breaks}</div>`;
  wrap.querySelectorAll('[data-mealtab]').forEach(b=>b.onclick=()=>{window.__activeMealId=b.dataset.mealtab;render()});
  const input=wrap.querySelector('input[type=file]');input.onchange=e=>{const f=e.target.files[0];if(f)compress(f,x=>{m.img=x;render()})};
  wrap.querySelectorAll('[data-subadd]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-subminus]'))return;const [g,k]=b.dataset.subadd.split(':');m.subCounts[g][k]=(Number(m.subCounts[g][k])||0)+(Number(g)===4?0.5:1);syncTotals(m);render()});
  wrap.querySelectorAll('[data-subminus]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const [g,k]=b.dataset.subminus.split(':');const step=Number(g)===4?0.5:1;m.subCounts[g][k]=Math.max(0,(Number(m.subCounts[g][k])||0)-step);syncTotals(m);render()});
  renderG3Support(d);const sum=renderBalance(document.getElementById('balance'),d);const a=document.getElementById('advice');a.textContent=sum.txt;a.className='advice '+sum.cls;
};

const guide=document.getElementById('guideView');guide.innerHTML=`<section class="section"><div class="card guideWheelWrap"><h2 style="margin:0 0 6px">四群点数法の見方</h2><p class="subtle">食べた食品を、4つの群とその内訳で確認します。</p><div class="guideWheel"><div class="guideQuad g1">第1群<small>牛乳・乳製品／卵</small></div><div class="guideQuad g2">第2群<small>魚介／肉／豆</small></div><div class="guideQuad g3">第3群<small>野菜／きのこ海藻／いも／果物</small></div><div class="guideQuad g4">第4群<small>主食／調味料／油脂／その他</small></div><div class="guideWheelCenter">1点＝80kcal</div></div></div><div class="card guidecard"><h2>3群の目安</h2><ul><li>野菜は1日350gを目安に。</li><li>緑黄色野菜は120g以上を目安にし、残りを淡色野菜で補います。</li><li>きのこ・海藻類は30〜40g/日を目安として記録できます。</li></ul></div><button type="button" class="backGuide" id="closeGuide">ダイアリーに戻る</button></section>`;

const today=document.getElementById('todayView'),progress=document.getElementById('progressView');const measureSec=document.querySelector('.measure')?.closest('.section'),healthSec=document.querySelector('.healthcheck')?.closest('.section');let healthView=document.getElementById('healthView');if(!healthView){healthView=document.createElement('main');healthView.id='healthView';healthView.className='view';healthView.innerHTML=`<section class="section"><div class="healthHero"><h2>おはようございます！！</h2><p>今日の体調はいかがですか？<br>今日も楽しく健康生活を目指しましょう！！</p></div></section>`;document.querySelector('.app').appendChild(healthView)}if(healthSec)healthView.appendChild(healthSec);if(measureSec){const card=measureSec.querySelector('.measure');if(card)card.querySelector('h2').textContent='体重・腹囲の記録';progress.querySelector('.section')?.prepend(measureSec)}
const nav=document.querySelector('.footnav>div');nav.innerHTML=`<button data-view="todayView" class="active">ダイアリー</button><button data-view="healthView">体調</button><button data-view="calendarView">カレンダー</button><button data-view="progressView">進捗</button><button data-view="settingsView">設定</button>`;const originalSwitch=switchView;switchView=function(id){originalSwitch(id);if(id==='healthView'){renderHealth(dayData());resetScrollTop()}};document.querySelectorAll('.footnav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
const oldOpen=document.getElementById('openGuide'),newOpen=oldOpen.cloneNode(true);oldOpen.replaceWith(newOpen);newOpen.textContent='四群の説明';newOpen.onclick=()=>{document.documentElement.style.setProperty('--guideTop',document.querySelector('.hero').offsetHeight+'px');switchView('guideView');guide.scrollTop=0};document.getElementById('closeGuide').onclick=()=>switchView('todayView');render();
})();